services:
#  app:
#    build: .
#    volumes:
#      - "./Hurts.lua:/app/Hurts.lua"

  db:
    image: mariadb:12
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=wow
      - MARIADB_PASSWORD=wow
      - MARIADB_DATABASE=wow
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
